---
title: "Okay, fine, we'll have a developer's blog"
description: "Obligatory first post about blog"
author: "David Nicholson"
date: "2024-02-11"
categories: [vocalpy, blog]
---

Hey, it's me, [David](https://nicholdav.info/).  

I'm the person who develops most of [this code](https://github.com/vocalpy). 
I'm interested in how animals communicate with sound, 
and I'm trying to make it easy for me and other reseachers to study 
this behavior computationally.

Hopefully, at some point, a team of people will work together to develop it, 
or something like it, once I can convince them that's a good idea.  
Then finally I can spend more time playing video games and birding, 
or doing whatever it is that people do when they're not being open source software maintainers.

First I have to convince more people that the ideas behind this code are good ideas. 
Recently I have realized that just writing the code isn't enough.
According to people who have been at this longer than I have, 
one way to talk people into things is to build not just a project, but a community. 
(See rule 5 [here](https://third-bit.com/ideas/advice/#talking-people-into-things), 
and notice I am ignoring rule 1.)
Well, I have been working on building a community:  
we have gotten a lot of contributors 
to at least one package, (vak)[https://github.com/vocalpy/vak?tab=readme-ov-file#contributors-].
And I am expecting to get more contributors to 
our core package [VocalPy](https://vocalpy.readthedocs.io/en/latest/), 
once we share results we are getting with it right now,
using newer features we have added and are adding.
We also have a growing number of people joining [our forum](https://forum.vocalpy.org/) and asking questions.

But it seems like I need to do more if I really want the community to grow.
I need to actually explain about what I'm doing here.

So, okay, fine, we will have a developer's blog.
And I guess right now that's the royal we--mainly it's just me.
Mainly this will be a place to post about new releases, 
and about research that uses the code.
Stay tuned for more.